# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0002_auto_20170222_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='sigma_core.Group'),
        ),
    ]
